# Prod environment overlay (non-sensitive values only)

env:
  OIDC_ISSUER_URI: https://login.microsoftonline.com/<prod-tenant-id>/v2.0
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.monitoring.svc.cluster.local:4317

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "2000m"
    memory: "2Gi"
