package io.poesis.sie.defman.config;

import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.ResourcePatternResolver;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * Seeds GSM base archetypes from {@code schemas/gsm-archetypes/*.schema.json}
 * classpath resources on first startup (idempotent — skips if archetypes
 * already exist).
 *
 * <p>
 * Uses raw JDBC. IDs and timestamps are generated by DB defaults/triggers.
 * The sync trigger ({@code trg_ast_sync_owner_status}) is temporarily disabled
 * so archetypes can be inserted with explicit {@code status=ACTIVE, version=1};
 * lifecycle transitions are inserted for audit trail completeness.
 *
 * <p>
 * Why disable the sync trigger: inserting 4 transitions in one transaction
 * causes the deferred constraint trigger
 * {@code tgf_assert_owner_status_matches_history}
 * to fail — it checks per-event snapshots against the final transition state,
 * and the original INSERT snapshot (status=DRAFT) mismatches the final
 * (ACTIVE).
 *
 * <p>
 * Schema files are sourced from {@code definition/schemas/gsm-archetypes/}
 * (mapped to classpath via Maven resource directory). Single source of truth:
 * edit schema files, restart — no migration changes needed.
 */
@Component
public class GsmBootstrapRunner implements ApplicationRunner {

    private static final Logger LOG = LoggerFactory.getLogger(GsmBootstrapRunner.class);
    private static final String SCHEMA_PATTERN = "classpath:schemas/gsm-archetypes/*.schema.json";

    private final JdbcTemplate jdbc;
    private final ObjectMapper mapper;
    private final ResourcePatternResolver resolver;

    public GsmBootstrapRunner(JdbcTemplate jdbc, ObjectMapper mapper,
            ResourcePatternResolver resolver) {
        this.jdbc = jdbc;
        this.mapper = mapper;
        this.resolver = resolver;
    }

    @Override
    @Transactional("transactionManager")
    public void run(ApplicationArguments args) throws Exception {
        Long count = jdbc.queryForObject("SELECT count(*) FROM archetype", Long.class);
        if (count != null && count > 0) {
            LOG.info("GSM base archetypes already seeded ({} row(s)); skipping bootstrap.", count);
            return;
        }
        doSeed();
    }

    private void doSeed() throws IOException {
        // Disable sync trigger — we insert with final status/version directly;
        // transitions are for audit trail only.
        jdbc.execute("ALTER TABLE ascription_status_transition DISABLE TRIGGER trg_ast_sync_owner_status");
        try {
            doSeedInternal();
        } finally {
            jdbc.execute("ALTER TABLE ascription_status_transition ENABLE TRIGGER trg_ast_sync_owner_status");
        }
    }

    private void doSeedInternal() throws IOException {
        Map<String, JsonNode> schemas = loadSchemas();

        // Meta-archetype must be seeded first (all others reference it)
        JsonNode metaSchema = schemas.remove("Archetype");
        if (metaSchema == null) {
            throw new IllegalStateException(
                    "Archetype.schema.json (title='Archetype') not found on classpath");
        }

        UUID metaDefId = insertDefinition();
        // Self-referential: id = archetype_id (CTE generates one UUID for both)
        UUID metaAscId = jdbc.queryForObject(
                "WITH gen AS (SELECT uuid_v7() AS v)"
                        + " INSERT INTO archetype (id, definition_id, archetype_id, statement, version, status)"
                        + " SELECT v, ?::uuid, v, ?::jsonb, 1, 'ACTIVE'::ascription_status FROM gen RETURNING id",
                UUID.class, metaDefId.toString(), wrapSchema(metaSchema));
        insertLifecycleTransitions(metaAscId);
        LOG.info("Seeded meta-archetype: Archetype (self-typed bootstrap)");

        for (Map.Entry<String, JsonNode> entry : schemas.entrySet()) {
            UUID defId = insertDefinition();
            UUID ascId = jdbc.queryForObject(
                    "INSERT INTO archetype (definition_id, archetype_id, statement, version, status)"
                            + " VALUES (?::uuid, ?::uuid, ?::jsonb, 1, 'ACTIVE'::ascription_status) RETURNING id",
                    UUID.class, defId.toString(), metaAscId.toString(),
                    wrapSchema(entry.getValue()));
            insertLifecycleTransitions(ascId);
            LOG.info("Seeded base archetype: {}", entry.getKey());
        }

        LOG.info("GSM bootstrap complete: {} base archetype(s) seeded.", 1 + schemas.size());
    }

    private Map<String, JsonNode> loadSchemas() throws IOException {
        Resource[] resources = resolver.getResources(SCHEMA_PATTERN);
        Map<String, JsonNode> schemas = new LinkedHashMap<>();
        for (Resource r : resources) {
            JsonNode schema = mapper.readTree(r.getInputStream());
            JsonNode titleNode = schema.get("title");
            if (titleNode == null || titleNode.asText().isBlank()) {
                throw new IllegalStateException(
                        "Schema file missing 'title': " + r.getFilename());
            }
            schemas.put(titleNode.asText(), schema);
        }
        if (schemas.isEmpty()) {
            throw new IllegalStateException("No schema files found at " + SCHEMA_PATTERN);
        }
        return schemas;
    }

    private UUID insertDefinition() {
        return jdbc.queryForObject(
                "INSERT INTO definition (subject_type)"
                        + " VALUES ('ARCHETYPE'::definition_subject_type) RETURNING id",
                UUID.class);
    }

    private void insertLifecycleTransitions(UUID ascriptionId) {
        String id = ascriptionId.toString();
        // Audit trail — sync trigger is disabled, status/version set at INSERT time
        jdbc.update(
                "INSERT INTO ascription_status_transition (ascription_id, pre_status, post_status)"
                        + " VALUES (?::uuid, NULL, 'DRAFT'::ascription_status)",
                id);
        jdbc.update(
                "INSERT INTO ascription_status_transition (ascription_id, pre_status, post_status)"
                        + " VALUES (?::uuid, 'DRAFT'::ascription_status, 'PROPOSED'::ascription_status)",
                id);
        jdbc.update(
                "INSERT INTO ascription_status_transition (ascription_id, pre_status, post_status)"
                        + " VALUES (?::uuid, 'PROPOSED'::ascription_status, 'APPROVED'::ascription_status)",
                id);
        jdbc.update(
                "INSERT INTO ascription_status_transition (ascription_id, pre_status, post_status)"
                        + " VALUES (?::uuid, 'APPROVED'::ascription_status, 'ACTIVE'::ascription_status)",
                id);
    }

    private static String wrapSchema(JsonNode schema) {
        return "{\"schema\":" + schema.toString() + "}";
    }
}
