package org.sif.sie.dm.model;

import com.fasterxml.jackson.databind.JsonNode;
import jakarta.persistence.Column;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.PrePersist;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.generator.EventType;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

/**
 * Abstract base for all 9 GSM class tables.
 * <p>
 * DB triggers handle:
 * <ul>
 *   <li>{@code revision_id} — generated by DB when NULL (V2 conditional trigger),
 *       or accepted from JPA when pre-set via {@link #ensureIds()}</li>
 *   <li>{@code revision_timestamp} — always DB-authoritative</li>
 *   <li>{@code status} — synced from latest status transition row</li>
 * </ul>
 */
@MappedSuperclass
public abstract class AbstractAscription {

    @Id
    @Column(name = "revision_id", nullable = false, updatable = false)
    private UUID revisionId;

    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    @Generated(event = EventType.INSERT)
    @Column(name = "revision_timestamp", insertable = false, updatable = false)
    private Instant revisionTimestamp;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "archetype_id", nullable = false, updatable = false)
    private ArchetypeEntity archetype;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "definition", nullable = false, columnDefinition = "jsonb")
    private JsonNode definition;

    @Column(name = "version")
    private Integer version;

    @Generated(event = EventType.INSERT)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "status", insertable = false, updatable = false)
    private AscriptionStatus status;

    @PrePersist
    void ensureIds() {
        if (revisionId == null) {
            revisionId = UuidV7.generate();
        }
        if (id == null) {
            id = UuidV7.generate();
        }
    }

    // ---- accessors ----

    public UUID getRevisionId() { return revisionId; }
    public void setRevisionId(UUID revisionId) { this.revisionId = revisionId; }

    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }

    public Instant getRevisionTimestamp() { return revisionTimestamp; }

    public ArchetypeEntity getArchetype() { return archetype; }
    public void setArchetype(ArchetypeEntity archetype) { this.archetype = archetype; }

    public JsonNode getDefinition() { return definition; }
    public void setDefinition(JsonNode definition) { this.definition = definition; }

    public Integer getVersion() { return version; }
    public void setVersion(Integer version) { this.version = version; }

    public AscriptionStatus getStatus() { return status; }

    // ---- equals / hashCode (Vlad Mihalcea pattern) ----

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AbstractAscription that = (AbstractAscription) o;
        return revisionId != null && Objects.equals(revisionId, that.revisionId);
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
