{{- $fullname := include "sie-event-bus-kafka.fullname" . -}}
{{- $secretName := printf "%s-kraft" $fullname -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
{{ include "sie-event-bus-kafka.labels" . | indent 4 }}
type: Opaque
data:
  {{- if and $existing $existing.data $existing.data.CLUSTER_ID }}
  CLUSTER_ID: {{ $existing.data.CLUSTER_ID }}
  {{- else if .Values.kraft.clusterId }}
  CLUSTER_ID: {{ .Values.kraft.clusterId | b64enc }}
  {{- else }}
  CLUSTER_ID: {{ randAlphaNum 22 | b64enc }}
  {{- end }}
