package cloud.poesis.sie.defman.entity;

import cloud.poesis.sie.defman.type.DefinitionSubjectType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.NamedSubgraph;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OrderBy;
import jakarta.persistence.Table;
import java.util.List;
import java.util.Objects;
import java.util.UUID;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * Stable identity of a governed subject in GSM.
 *
 * <p>A Definition answers <em>what thing is being governed</em> — the referent that persists across
 * all Ascriptions (normative snapshots) that describe it over time. Definition does NOT extend
 * Ascription; it is a separate entity providing the identity anchor.
 *
 * <p>Maps to the {@code definition} table. Both fields ({@code id}, {@code subjectType}) are
 * immutable after creation — assigned via constructor, no setters exposed.
 *
 * <p>No triggers on this table. {@code id} is generated by the column default {@code uuid_v7()}
 * (DB-side, not application-generated).
 *
 * @author Clément Cazaud
 * @since 1.0.0
 */
@Entity
@Table(name = "definition")
@NamedEntityGraph(
    name = "definition-with-ascription-archetypes",
    attributeNodes = @NamedAttributeNode(value = "ascriptions", subgraph = "ascription-archetype"),
    subgraphs =
        @NamedSubgraph(
            name = "ascription-archetype",
            attributeNodes = @NamedAttributeNode("archetype")))
public class DefinitionEntity {

  @Id
  @GeneratedValue()
  @Column(name = "id", nullable = false, updatable = false, insertable = false)
  private UUID id;

  @JdbcTypeCode(SqlTypes.NAMED_ENUM)
  @Column(name = "subject_type", nullable = false, updatable = false)
  private DefinitionSubjectType subjectType;

  @OneToMany(mappedBy = "definition", fetch = FetchType.LAZY)
  @OrderBy("timestamp DESC")
  private List<AscriptionEntity> ascriptions;

  /** JPA requires a no-arg constructor. */
  protected DefinitionEntity() {}

  /**
   * Creates a new Definition with the given subject type.
   *
   * @param subjectType the GSM structural role of this subject (immutable once assigned)
   */
  public DefinitionEntity(DefinitionSubjectType subjectType) {
    this.subjectType = Objects.requireNonNull(subjectType, "subjectType");
  }

  // ---- accessors (read-only) ----

  /**
   * Returns the globally unique identity of this Definition (UUIDv7).
   *
   * @return the definition id, never {@code null}
   */
  public UUID getId() {
    return id;
  }

  /**
   * Returns the GSM structural role of this subject.
   *
   * @return the subject type, never {@code null}
   */
  public DefinitionSubjectType getSubjectType() {
    return subjectType;
  }

  /**
   * Returns all Ascriptions referencing this Definition, ordered by timestamp descending.
   *
   * @return the ascription list, never {@code null}
   */
  public List<AscriptionEntity> getAscriptions() {
    return ascriptions;
  }

  // ---- equals / hashCode ----

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    DefinitionEntity that = (DefinitionEntity) o;
    return id != null && Objects.equals(id, that.id);
  }

  @Override
  public int hashCode() {
    return getClass().hashCode();
  }
}
