package com.sif.sie.definitionmanager.entity;

import com.fasterxml.jackson.databind.JsonNode;
import com.sif.sie.definitionmanager.enums.AscriptionStatus;
import com.sif.sie.definitionmanager.util.UuidV7Generator;
import jakarta.persistence.Column;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.PrePersist;
import java.time.Instant;
import java.util.Objects;
import java.util.UUID;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * Abstract base for all 9 GSM class tables.
 *
 * <p>Maps the GSM Ascription concept: a governed normative snapshot of a Definition. Each row is an
 * immutable snapshot whose identity ({@code id}) is distinct from the stable subject identity held
 * by the referenced {@link DefinitionEntity}.
 *
 * <p>Immutable-after-creation fields ({@code definition}, {@code archetype}, {@code statement}) are
 * set via constructor. The only mutable field is {@code version} (assigned at APPROVED transition).
 *
 * <p>DB triggers handle:
 *
 * <ul>
 *   <li>{@code id} (PK) — generated by DB when NULL (conditional trigger), or accepted from JPA
 *       when pre-set via {@link #ensureId()}
 *   <li>{@code timestamp} — always DB-authoritative
 *   <li>{@code status} — synced from latest status transition row
 * </ul>
 */
@MappedSuperclass
public abstract class AbstractAscription {

    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "definition_id", nullable = false, updatable = false)
    private DefinitionEntity definition;

    @Column(name = "\"timestamp\"", insertable = false, updatable = false)
    private Instant timestamp;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "archetype_id", nullable = false, updatable = false)
    private ArchetypeEntity archetype;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "statement", nullable = false, columnDefinition = "jsonb")
    private JsonNode statement;

    @Column(name = "version")
    private Integer version;

    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "status", insertable = false, updatable = false)
    private AscriptionStatus status;

    /** JPA requires a no-arg constructor. */
    protected AbstractAscription() {}

    protected AbstractAscription(
            DefinitionEntity definition, ArchetypeEntity archetype, JsonNode statement) {
        this.definition = definition;
        this.archetype = archetype;
        this.statement = statement;
    }

    @PrePersist
    void ensureId() {
        if (id == null) {
            id = UuidV7Generator.generate();
        }
    }

    // ---- accessors ----

    public UUID getId() {
        return id;
    }

    public DefinitionEntity getDefinition() {
        return definition;
    }

    public Instant getTimestamp() {
        return timestamp;
    }

    public ArchetypeEntity getArchetype() {
        return archetype;
    }

    public JsonNode getStatement() {
        return statement;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public AscriptionStatus getStatus() {
        return status;
    }

    // ---- equals / hashCode (Vlad Mihalcea pattern) ----

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AbstractAscription that = (AbstractAscription) o;
        return id != null && Objects.equals(id, that.id);
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
