package com.sif.sie.definitionmanager.entity;

import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import org.springframework.lang.NonNull;

import com.fasterxml.jackson.databind.JsonNode;
import com.sif.sie.definitionmanager.type.AscriptionStatusType;
import com.sif.sie.definitionmanager.util.UuidV7GeneratorUtil;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.Inheritance;
import jakarta.persistence.InheritanceType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;

/**
 * Abstract base for all 9 GSM class tables.
 *
 * <p>
 * Maps the GSM Ascription concept: a governed normative snapshot of a
 * Definition. Each row is an immutable snapshot whose identity ({@code id})
 * is distinct from the stable subject identity held by the referenced
 * {@link DefinitionEntity}.
 *
 * <p>
 * Immutable-after-creation fields ({@code definition}, {@code archetype},
 * {@code compilation}) are set via constructor. All other fields
 * ({@code timestamp}, {@code status}, {@code version}) are DB
 * trigger-managed — no setters exposed.
 *
 * <p>
 * DB triggers handle:
 *
 * <ul>
 * <li>{@code id} (PK) — generated by DB when NULL (conditional trigger), or
 * accepted from JPA when pre-set via {@link #ensureId()}
 * <li>{@code timestamp} — always DB-authoritative
 * <li>{@code status} — synced from latest status transition row by DB trigger
 * <li>{@code version} — assigned atomically by DB trigger on APPROVED
 * transition
 * </ul>
 *
 * <p>
 * Column insertable/updatable rationale:
 * <ul>
 * <li>{@code id} — insertable (JPA generates via @PrePersist), not updatable
 * <li>{@code definition_id}, {@code archetype_id},
 * {@code compilation} — insertable, not updatable (immutable-after-creation)
 * <li>{@code timestamp}, {@code status}, {@code version} — neither insertable
 * nor updatable (DB trigger-managed exclusively)
 * </ul>
 */
@SuppressWarnings("null") // JPA lifecycle: fields are always populated when accessed
@Entity
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
public abstract class AscriptionEntity {

    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "definition_id", nullable = false, updatable = false)
    private DefinitionEntity definition;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "archetype_id", nullable = false, updatable = false)
    private ArchetypeEntity archetype;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "compilation", nullable = false, updatable = false, columnDefinition = "jsonb")
    private JsonNode compilation;

    @Column(name = "\"timestamp\"", nullable = false, updatable = false, insertable = false)
    private Instant timestamp;

    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "status", nullable = false, updatable = false, insertable = false)
    private AscriptionStatusType status;

    @Column(name = "version", nullable = false, updatable = false, insertable = false)
    private Integer version;

    /** JPA requires a no-arg constructor. */
    protected AscriptionEntity() {
    }

    protected AscriptionEntity(
            DefinitionEntity definition, ArchetypeEntity archetype, JsonNode compilation) {
        this.definition = Objects.requireNonNull(definition, "definition");
        this.archetype = Objects.requireNonNull(archetype, "archetype");
        this.compilation = Objects.requireNonNull(compilation, "compilation");
    }

    @PrePersist
    void ensureId() {
        if (id == null) {
            id = UuidV7GeneratorUtil.generate();
        }
    }

    // ---- accessors ----

    @NonNull
    public UUID getId() {
        return id;
    }

    @NonNull
    public DefinitionEntity getDefinition() {
        return definition;
    }

    @NonNull
    public ArchetypeEntity getArchetype() {
        return archetype;
    }

    @NonNull
    public JsonNode getCompilation() {
        return compilation;
    }

    @NonNull
    public Instant getTimestamp() {
        return timestamp;
    }

    @NonNull
    public AscriptionStatusType getStatus() {
        return status;
    }

    public int getVersion() {
        return version;
    }

    // ---- equals / hashCode (Vlad Mihalcea pattern) ----

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;
        AscriptionEntity that = (AscriptionEntity) o;
        return id != null && Objects.equals(id, that.id);
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
