apiVersion: v2
name: sie-definition-manager
description: Umbrella chart for SIE Definition Manager and its dependencies
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: sie-event-bus-kafka
    version: "0.1.0"
    repository: "file://../../../sie-event-bus/ops/helm"
    alias: eventbus
  - name: sie-schema-registry
    version: "0.1.0"
    repository: "file://../../../sie-schema-registry/ops/helm"
    alias: schemaregistry
  - name: sie-definition-database
    version: "0.1.0"
    repository: "file://../../../sie-definition-database/ops/helm"
    alias: definitiondatabase
