package cloud.poesis.sie.defman.bootstrap;

import cloud.poesis.sie.defman.service.ArchetypeParsingService;
import cloud.poesis.sie.defman.service.ArchetypeService;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.ResourcePatternResolver;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Seeds GSM base archetypes from {@code gsm/schemas/*.json} classpath resources
 * on first startup
 * (idempotent — skips if archetypes already exist).
 *
 * <p>
 * Uses raw JDBC. IDs and timestamps are generated by DB defaults/triggers. The
 * status-sync
 * trigger is temporarily disabled so archetypes can be inserted with explicit
 * {@code status=ACTIVE}
 * and {@code version=1}; lifecycle transitions are inserted for audit trail
 * completeness.
 *
 * <p>
 * Why disable the sync trigger: {@code tgf_sync_ascription_status} would
 * redundantly walk the
 * archetype row through DRAFT→PROPOSED→APPROVED→ACTIVE when we already set
 * ACTIVE directly at
 * INSERT time.
 *
 * <p>
 * Schema files are sourced from {@code src/main/resources/gsm/schemas/} (a
 * pinned snapshot of
 * the gsm-specifications repo). Single source of truth: edit schema files,
 * restart — no migration
 * changes needed.
 *
 * @author Clément Cazaud
 * @since 1.0.0
 */
@Component
@ConditionalOnProperty(name = "dm.bootstrap.enabled", havingValue = "true", matchIfMissing = true)
public class ArchetypeSeedRunner implements ApplicationRunner {

  private static final Logger LOG = LoggerFactory.getLogger(ArchetypeSeedRunner.class);

  private final JdbcTemplate jdbc;
  private final ObjectMapper mapper;
  private final ResourcePatternResolver resolver;
  private final String schemaPattern;
  private final ArchetypeService archetypeService;

  /**
   * Constructs the seed runner.
   *
   * @param jdbc             JDBC template for raw SQL operations
   * @param mapper           Jackson mapper for JSON schema parsing
   * @param resolver         classpath resource resolver
   * @param schemaPattern    glob pattern for GSM archetype schema files
   * @param archetypeService the Archetype service owning index provisioning
   */
  public ArchetypeSeedRunner(
      JdbcTemplate jdbc,
      ObjectMapper mapper,
      ResourcePatternResolver resolver,
      @Value("${dm.bootstrap.archetype-schema-pattern}") String schemaPattern,
      ArchetypeService archetypeService) {
    this.jdbc = jdbc;
    this.mapper = mapper;
    this.resolver = resolver;
    this.schemaPattern = schemaPattern;
    this.archetypeService = archetypeService;
  }

  @Override
  @Transactional("transactionManager")
  public void run(ApplicationArguments args) throws Exception {
    Long count = jdbc.queryForObject("SELECT count(*) FROM archetype", Long.class);
    if (count != null && count > 0) {
      reconcileExistingStemOwners();
      LOG.info(
          "GSM base archetypes already seeded ({} row(s)); reconciled stem ownership and skipped bootstrap.",
          count);
    } else {
      doSeed();
    }
    // Bases are inserted at ACTIVE, so they never reach ArchetypeService#onActivation.
    LOG.info(
        "Provisioned property indexes for {} GSM base archetype(s).",
        archetypeService.reconcileBaseArchetypeIndexes());
  }

  private void doSeed() throws IOException {
    // Disable sync trigger — we insert with final status directly;
    // transitions are for audit trail only.
    jdbc.execute(
        "ALTER TABLE ascription_status_transition DISABLE TRIGGER trg_ast_sync_ascription_status");
    try {
      doSeedInternal();
    } finally {
      jdbc.execute(
          "ALTER TABLE ascription_status_transition ENABLE TRIGGER trg_ast_sync_ascription_status");
    }
  }

  private void doSeedInternal() throws IOException {
    Map<String, JsonNode> schemas = loadSchemas();

    // Meta-archetype must be seeded first (all others reference it)
    JsonNode axiomaticArchetypeSchema = schemas.remove("Archetype");
    if (axiomaticArchetypeSchema == null) {
      throw new IllegalStateException(
          "Archetype.schema.json (title='Archetype') not found on classpath");
    }

    UUID axiomaticDefinitionId = insertDefinition();
    // Self-referential: id = archetype_id (CTE generates one UUID for both)
    UUID axiomaticArchetypeId = Objects.requireNonNull(
        jdbc.queryForObject(
            "WITH gen AS (SELECT uuid_v7() AS v)"
                + " INSERT INTO archetype"
                + " (id, definition_id, archetype_id, statement, status, version)"
                + " SELECT v, ?::uuid, v, ?::jsonb, 'ACTIVE'::ascription_status, 1"
                + " FROM gen RETURNING id",
            UUID.class,
            axiomaticDefinitionId.toString(),
            axiomaticArchetypeSchema.toString()));
    claimOrVerifyStemOwner(axiomaticArchetypeSchema, axiomaticDefinitionId);
    insertLifecycleTransitions(axiomaticArchetypeId);
    LOG.info("Seeded meta-archetype: Archetype (self-typed bootstrap)");

    for (Map.Entry<String, JsonNode> entry : schemas.entrySet()) {
      UUID definitionId = insertDefinition();
      UUID archetypeId = Objects.requireNonNull(
          jdbc.queryForObject(
              "INSERT INTO archetype"
                  + " (definition_id, archetype_id, statement, status, version)"
                  + " VALUES (?::uuid, ?::uuid, ?::jsonb, 'ACTIVE'::ascription_status, 1)"
                  + " RETURNING id",
              UUID.class,
              definitionId.toString(),
              axiomaticArchetypeId.toString(),
              entry.getValue().toString()));
      claimOrVerifyStemOwner(entry.getValue(), definitionId);
      insertLifecycleTransitions(archetypeId);
      LOG.info("Seeded base archetype: {}", entry.getKey());
    }

    LOG.info("GSM bootstrap complete: {} base archetype(s) seeded.", 1 + schemas.size());
  }

  private Map<String, JsonNode> loadSchemas() throws IOException {
    Resource[] resources = resolver.getResources(schemaPattern);
    Map<String, JsonNode> schemas = new LinkedHashMap<>();
    for (Resource resource : resources) {
      JsonNode schema = mapper.readTree(resource.getInputStream());
      JsonNode titleNode = schema.get("title");
      if (titleNode == null || titleNode.asText().isBlank()) {
        throw new IllegalStateException("Schema file missing 'title': " + resource.getFilename());
      }
      schemas.put(titleNode.asText(), schema);
    }
    if (schemas.isEmpty()) {
      throw new IllegalStateException("No schema files found at " + schemaPattern);
    }
    return schemas;
  }

  private UUID insertDefinition() {
    return jdbc.queryForObject(
        "INSERT INTO definition (subject_type)"
            + " VALUES ('ARCHETYPE'::definition_subject_type) RETURNING id",
        UUID.class);
  }

  private void reconcileExistingStemOwners() {
    jdbc.queryForList("SELECT statement->>'$id' AS statement_id, definition_id FROM archetype")
        .forEach(
            row -> {
              String statementId = (String) row.get("statement_id");
              UUID definitionId = (UUID) row.get("definition_id");
              claimOrVerifyStemOwner(statementId, definitionId);
            });
  }

  private void claimOrVerifyStemOwner(JsonNode schema, UUID definitionId) {
    claimOrVerifyStemOwner(schema.path("$id").asText(), definitionId);
  }

  private void claimOrVerifyStemOwner(String statementId, UUID definitionId) {
    String stem = ArchetypeParsingService.parseIdentity(statementId).stem();
    UUID ownerDefinitionId = jdbc.queryForObject(
        "SELECT gsm_acquire_archetype_stem_owner(?::text, ?::uuid)",
        UUID.class,
        stem,
        definitionId.toString());
    if (!definitionId.equals(ownerDefinitionId)) {
      throw new IllegalStateException(
          "Seed Archetype stem '"
              + stem
              + "' claimed by Definition "
              + definitionId
              + " is owned by Definition "
              + ownerDefinitionId);
    }
  }

  private void insertLifecycleTransitions(UUID ascriptionId) {
    String id = ascriptionId.toString();
    // Audit trail — sync trigger is disabled, status set at INSERT time
    jdbc.update(
        "INSERT INTO ascription_status_transition (ascription_id, pre_status, post_status)"
            + " VALUES (?::uuid, 'DRAFT'::ascription_status, 'PROPOSED'::ascription_status)",
        id);
    jdbc.update(
        "INSERT INTO ascription_status_transition (ascription_id, pre_status, post_status)"
            + " VALUES (?::uuid, 'PROPOSED'::ascription_status, 'APPROVED'::ascription_status)",
        id);
    jdbc.update(
        "INSERT INTO ascription_status_transition (ascription_id, pre_status, post_status)"
            + " VALUES (?::uuid, 'APPROVED'::ascription_status, 'ACTIVE'::ascription_status)",
        id);
  }
}
