{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sie-schema-registry.serviceAccountName" . }}
  labels:
    {{- include "sie-schema-registry.labels" . | nindent 4 }}
{{- end }}
